### ISSUE TITLE
smart-cube-timer with chrome-beta under windows 10

### ISSUE THREAD

**Issue by amibuttons** [hakatashi/smart-cube-timer#1]
Hi,

I was able to pair the cube under windows 10 with chrome beta. 

I started chrome with --enable-features=NewBLEWinImplementation and enabled chrome://flags/#enable-experimental-web-platform-features.

After selecting the cube in the device selector, the cube appears to have been paired. However your web-app throws the following error message:

No Characteristics matching UUID 0000aadc-0000-1000-8000-00805f9b34fb found in Service with UUID 0000aadb-0000-1000-8000-00805f9b34fb.

at the bottom of the page.

This might not be an issue at your end, singe the webbluetooth implementation on windows 10 is spotty. However, if you got an idea how to make your timer work on  windows 10, that would be great.

Thanks
amiB

**Comment by hakatashi** [comment]
Thanks very useful info @amibuttons 😂 I'll check it out later!

**Comment by amibuttons** [comment]
Hi,

instead of chrome beta i used chrome-dev a described on the wikipage:

https://github.com/hakatashi/smart-cube-timer/wiki/Windows-Guide

Works fine with chrome-dev.

Don't forget to --enable-features=NewBLEWinImplementation and enable chrome://flags/#enable-experimental-web-platform-features.

Thanks, since the whole issue lies with the spotty implemenation of webluetooth under windows. I'm closing this issue.
