### ISSUE TITLE
Link OLL and PLL to algdb.net

### ISSUE THREAD

**Issue by Reo1980** [hakatashi/smart-cube-timer#17]
Hi. Is it possible to link the OLL <X> and PLL <X Perm> to algdb.net?

In solve details i will get OLL 19 and it is nice to have direct link to http://algdb.net/puzzle/333/oll/oll19

Thanks a lot to share this project!

**Comment by hugopeeters** [comment]
I just wanted to comment to say:
- I absolutely LOVE this project. I can't stop practicing solves with it.
- One thing I HATE.... I can't get around learning G-perms now. It's so obvious I suck at them... ;)

**Comment by hugopeeters** [comment]
Hey , I got the code working on my own system. I have been able to add these hyperlinks and I'd like to create a pull request to close out this issue. I have never done a pull request before, so I would like some instructions please. Thanks!
