### ISSUE TITLE
Recognize orientation

### ISSUE THREAD

**Issue by hugopeeters** [hakatashi/smart-cube-timer#19]
Would it be possible to recognize the initial orientation of the cube (i.e. before scramble) based on the first move? It appears it now assumes white top, green front when starting a scamble.
Say the first move of the scamble is an R, but since I have yellow top, red front, you detect an F instead. Based off that, you could probably deduct my cube's orientation.

**Comment by hugopeeters** [comment]
Alternatively, you could just add a comment how to orient pre-scramble to avoid confusion.

**Comment by tussosedan** [comment]
White top and green front is the standard WCA orientation.

**Comment by hugopeeters** [comment]
> White top and green front is the standard WCA orientation.

Oh? I never knew. Maybe just a comment would be the best solution then?

**Comment by hakatashi** [comment]
Ok. I'll modify description.
