### ISSUE TITLE
Add "reset by solve" button

### ISSUE THREAD

**Issue by cucumberbob123** [hakatashi/smart-cube-timer#26]
Sometimes, the app thinks that my cube is not solved when it is. My current solution to this problem is to refresh the page, and reconnect the cube, but this can take up to a minute. If there was a button I could press that reset the cube, so the app knew my cube was solved, that would be excellent.

Thanks for making such a brilliant webapp!

**Comment by hakatashi** [comment]
Thank you for your report😉 Maybe this is dup of #15?
