### ISSUE TITLE
Bluetooth adapter not available.

### ISSUE THREAD

**Issue by Reo1980** [hakatashi/smart-cube-timer#4]
Hi. I follow the instructions (https://github.com/hakatashi/smart-cube-timer/wiki/Windows-Guide) but I can't connect to my cube. Are there any possible reason I can check to fix this issue? (Can I get more detailed error log to support?)
Using Dell Laptop with Windows 10. (On my android smartphone pairing is no problem)

**Comment by amibuttons** [comment]
I'm using chrome-dev under windows 10 and it works flawlessly. After toggling chrome://flags/#enable-experimental-web-platform-features to enabled you need to restart the browser. And you need to start the browser with --enable-features=NewBLEWinImplementation either from the command prompt or by editing the windows shortcut.

**Comment by Reo1980** [comment]
Thanks, I fix the issue by using an other bluetooth adapter. Think it is an hardware issue with integrated bluetooth on my notebook. So it is no problem with your solution.
Can be closed. Thanks for support.
