### ISSUE TITLE
Adjust moves orientation after finishing First Block with Roux

### ISSUE THREAD

**Issue by tussosedan** [hakatashi/smart-cube-timer#7]
When FB is done, we can assume that it's on the left, and adjust the orientation of the cube and all the recorded moves accordingly.

**Comment by tussosedan** [comment]
Woooo!

**Comment by hakatashi** [comment]
![image](https://user-images.githubusercontent.com/3126484/45565869-02686e80-b890-11e8-9296-657523185d8e.png)

Now deployed. Definitely it's silly to see tons of `r R`s, but maybe I can implement recognition of M move sooner or later😏

**Comment by tussosedan** [comment]
This is so close to perfect! Slice moves would be awesome :)

**Comment by tussosedan** [comment]
@hakatashi at the very least I think it's safe to assume that all possible M/M' slice moves during a Roux solve really are slice moves. While Rouxers can do something like (U D') during first block, which is not an E slice, this would never happen with M.

**Comment by tussosedan** [comment]
Also during LSE all slices are definitely slices, including E and S
